# Generated by Django 6.1 on 2026-08-24 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={},
        ),
        migrations.AlterModelOptions(
            name="expense",
            options={},
        ),
        migrations.RemoveField(
            model_name="expense",
            name="created_at",
        ),
        migrations.AddField(
            model_name="expense",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expenses",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="expense",
            name="amount_cents",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="expense",
            name="comment",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterModelTable(
            name="category",
            table="core_category",
        ),
        migrations.AlterModelTable(
            name="expense",
            table="core_expense",
        ),
    ]
