# Generated by Django 6.1 on 2026-08-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_category_options_alter_expense_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="amount_cents",
            field=models.PositiveIntegerField(),
        ),
    ]
