# Generated by Django 6.1 on 2026-08-26 16:02

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_expense_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
    ]
