# Generated by Django 6.1 on 2026-08-26 16:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_expense_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="expense",
            options={"ordering": ["-spent_at", "-id"]},
        ),
    ]
