# Generated by Django 6.1 on 2026-08-26 17:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_category_options_alter_expense_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="expense",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_cents__gt", 0)), name="core_expense_amount_positive"
            ),
        ),
    ]
