# Generated by Django 6.1 on 2026-08-26 17:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_auto_20260826_2018"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(fields=["user", "spent_at"], name="expense_user_spent_idx"),
        ),
    ]
