# Generated by Django 6.1 on 2026-08-26 20:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_expense_expense_user_spent_idx"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="expense",
            name="core_expense_amount_positive",
        ),
    ]
